info:
  contact:
    name: Developer
    url: https://github.com/subhadeepdas91
  description: This project provide REST API to intract with SAP RFC
  termsOfService: http://swagger.io/terms/
  title: SAP RFC Bridge
  version: "1.0"
paths:
  /ping:
    get:
      description: Display Connection Details
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Dispaly Connection Details
swagger: "2.0"
